// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RegisterReq struct {
	Phone string `json:"phone"`
	Name  string `json:"name"`
}

type LoginReq struct {
	Phone string `json:"phone"`
}
