// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stark-sim/cas/pkg/ent/predicate"
	"github.com/stark-sim/cas/pkg/ent/role"
	"github.com/stark-sim/cas/pkg/ent/user"
	"github.com/stark-sim/cas/pkg/ent/userrole"
)

// UserRoleUpdate is the builder for updating UserRole entities.
type UserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *UserRoleMutation
}

// Where appends a list predicates to the UserRoleUpdate builder.
func (uru *UserRoleUpdate) Where(ps ...predicate.UserRole) *UserRoleUpdate {
	uru.mutation.Where(ps...)
	return uru
}

// SetCreatedBy sets the "created_by" field.
func (uru *UserRoleUpdate) SetCreatedBy(i int64) *UserRoleUpdate {
	uru.mutation.ResetCreatedBy()
	uru.mutation.SetCreatedBy(i)
	return uru
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableCreatedBy(i *int64) *UserRoleUpdate {
	if i != nil {
		uru.SetCreatedBy(*i)
	}
	return uru
}

// AddCreatedBy adds i to the "created_by" field.
func (uru *UserRoleUpdate) AddCreatedBy(i int64) *UserRoleUpdate {
	uru.mutation.AddCreatedBy(i)
	return uru
}

// SetUpdatedBy sets the "updated_by" field.
func (uru *UserRoleUpdate) SetUpdatedBy(i int64) *UserRoleUpdate {
	uru.mutation.ResetUpdatedBy()
	uru.mutation.SetUpdatedBy(i)
	return uru
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableUpdatedBy(i *int64) *UserRoleUpdate {
	if i != nil {
		uru.SetUpdatedBy(*i)
	}
	return uru
}

// AddUpdatedBy adds i to the "updated_by" field.
func (uru *UserRoleUpdate) AddUpdatedBy(i int64) *UserRoleUpdate {
	uru.mutation.AddUpdatedBy(i)
	return uru
}

// SetUpdatedAt sets the "updated_at" field.
func (uru *UserRoleUpdate) SetUpdatedAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetUpdatedAt(t)
	return uru
}

// SetDeletedAt sets the "deleted_at" field.
func (uru *UserRoleUpdate) SetDeletedAt(t time.Time) *UserRoleUpdate {
	uru.mutation.SetDeletedAt(t)
	return uru
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uru *UserRoleUpdate) SetNillableDeletedAt(t *time.Time) *UserRoleUpdate {
	if t != nil {
		uru.SetDeletedAt(*t)
	}
	return uru
}

// SetUserID sets the "user_id" field.
func (uru *UserRoleUpdate) SetUserID(i int64) *UserRoleUpdate {
	uru.mutation.SetUserID(i)
	return uru
}

// SetRoleID sets the "role_id" field.
func (uru *UserRoleUpdate) SetRoleID(i int64) *UserRoleUpdate {
	uru.mutation.SetRoleID(i)
	return uru
}

// SetUser sets the "user" edge to the User entity.
func (uru *UserRoleUpdate) SetUser(u *User) *UserRoleUpdate {
	return uru.SetUserID(u.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (uru *UserRoleUpdate) SetRole(r *Role) *UserRoleUpdate {
	return uru.SetRoleID(r.ID)
}

// Mutation returns the UserRoleMutation object of the builder.
func (uru *UserRoleUpdate) Mutation() *UserRoleMutation {
	return uru.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uru *UserRoleUpdate) ClearUser() *UserRoleUpdate {
	uru.mutation.ClearUser()
	return uru
}

// ClearRole clears the "role" edge to the Role entity.
func (uru *UserRoleUpdate) ClearRole() *UserRoleUpdate {
	uru.mutation.ClearRole()
	return uru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uru *UserRoleUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	uru.defaults()
	if len(uru.hooks) == 0 {
		if err = uru.check(); err != nil {
			return 0, err
		}
		affected, err = uru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uru.check(); err != nil {
				return 0, err
			}
			uru.mutation = mutation
			affected, err = uru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uru.hooks) - 1; i >= 0; i-- {
			if uru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uru *UserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := uru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uru *UserRoleUpdate) Exec(ctx context.Context) error {
	_, err := uru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uru *UserRoleUpdate) ExecX(ctx context.Context) {
	if err := uru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uru *UserRoleUpdate) defaults() {
	if _, ok := uru.mutation.UpdatedAt(); !ok {
		v := userrole.UpdateDefaultUpdatedAt()
		uru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uru *UserRoleUpdate) check() error {
	if _, ok := uru.mutation.UserID(); uru.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserRole.user"`)
	}
	if _, ok := uru.mutation.RoleID(); uru.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserRole.role"`)
	}
	return nil
}

func (uru *UserRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userrole.Table,
			Columns: userrole.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: userrole.FieldID,
			},
		},
	}
	if ps := uru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uru.mutation.CreatedBy(); ok {
		_spec.SetField(userrole.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.AddedCreatedBy(); ok {
		_spec.AddField(userrole.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.UpdatedBy(); ok {
		_spec.SetField(userrole.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(userrole.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.UpdatedAt(); ok {
		_spec.SetField(userrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uru.mutation.DeletedAt(); ok {
		_spec.SetField(userrole.FieldDeletedAt, field.TypeTime, value)
	}
	if uru.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uru.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uru.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: role.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uru.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// UserRoleUpdateOne is the builder for updating a single UserRole entity.
type UserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRoleMutation
}

// SetCreatedBy sets the "created_by" field.
func (uruo *UserRoleUpdateOne) SetCreatedBy(i int64) *UserRoleUpdateOne {
	uruo.mutation.ResetCreatedBy()
	uruo.mutation.SetCreatedBy(i)
	return uruo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableCreatedBy(i *int64) *UserRoleUpdateOne {
	if i != nil {
		uruo.SetCreatedBy(*i)
	}
	return uruo
}

// AddCreatedBy adds i to the "created_by" field.
func (uruo *UserRoleUpdateOne) AddCreatedBy(i int64) *UserRoleUpdateOne {
	uruo.mutation.AddCreatedBy(i)
	return uruo
}

// SetUpdatedBy sets the "updated_by" field.
func (uruo *UserRoleUpdateOne) SetUpdatedBy(i int64) *UserRoleUpdateOne {
	uruo.mutation.ResetUpdatedBy()
	uruo.mutation.SetUpdatedBy(i)
	return uruo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableUpdatedBy(i *int64) *UserRoleUpdateOne {
	if i != nil {
		uruo.SetUpdatedBy(*i)
	}
	return uruo
}

// AddUpdatedBy adds i to the "updated_by" field.
func (uruo *UserRoleUpdateOne) AddUpdatedBy(i int64) *UserRoleUpdateOne {
	uruo.mutation.AddUpdatedBy(i)
	return uruo
}

// SetUpdatedAt sets the "updated_at" field.
func (uruo *UserRoleUpdateOne) SetUpdatedAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetUpdatedAt(t)
	return uruo
}

// SetDeletedAt sets the "deleted_at" field.
func (uruo *UserRoleUpdateOne) SetDeletedAt(t time.Time) *UserRoleUpdateOne {
	uruo.mutation.SetDeletedAt(t)
	return uruo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uruo *UserRoleUpdateOne) SetNillableDeletedAt(t *time.Time) *UserRoleUpdateOne {
	if t != nil {
		uruo.SetDeletedAt(*t)
	}
	return uruo
}

// SetUserID sets the "user_id" field.
func (uruo *UserRoleUpdateOne) SetUserID(i int64) *UserRoleUpdateOne {
	uruo.mutation.SetUserID(i)
	return uruo
}

// SetRoleID sets the "role_id" field.
func (uruo *UserRoleUpdateOne) SetRoleID(i int64) *UserRoleUpdateOne {
	uruo.mutation.SetRoleID(i)
	return uruo
}

// SetUser sets the "user" edge to the User entity.
func (uruo *UserRoleUpdateOne) SetUser(u *User) *UserRoleUpdateOne {
	return uruo.SetUserID(u.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (uruo *UserRoleUpdateOne) SetRole(r *Role) *UserRoleUpdateOne {
	return uruo.SetRoleID(r.ID)
}

// Mutation returns the UserRoleMutation object of the builder.
func (uruo *UserRoleUpdateOne) Mutation() *UserRoleMutation {
	return uruo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (uruo *UserRoleUpdateOne) ClearUser() *UserRoleUpdateOne {
	uruo.mutation.ClearUser()
	return uruo
}

// ClearRole clears the "role" edge to the Role entity.
func (uruo *UserRoleUpdateOne) ClearRole() *UserRoleUpdateOne {
	uruo.mutation.ClearRole()
	return uruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uruo *UserRoleUpdateOne) Select(field string, fields ...string) *UserRoleUpdateOne {
	uruo.fields = append([]string{field}, fields...)
	return uruo
}

// Save executes the query and returns the updated UserRole entity.
func (uruo *UserRoleUpdateOne) Save(ctx context.Context) (*UserRole, error) {
	var (
		err  error
		node *UserRole
	)
	uruo.defaults()
	if len(uruo.hooks) == 0 {
		if err = uruo.check(); err != nil {
			return nil, err
		}
		node, err = uruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserRoleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uruo.check(); err != nil {
				return nil, err
			}
			uruo.mutation = mutation
			node, err = uruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uruo.hooks) - 1; i >= 0; i-- {
			if uruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uruo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, uruo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*UserRole)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from UserRoleMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) SaveX(ctx context.Context) *UserRole {
	node, err := uruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uruo *UserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := uruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uruo *UserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := uruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uruo *UserRoleUpdateOne) defaults() {
	if _, ok := uruo.mutation.UpdatedAt(); !ok {
		v := userrole.UpdateDefaultUpdatedAt()
		uruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uruo *UserRoleUpdateOne) check() error {
	if _, ok := uruo.mutation.UserID(); uruo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserRole.user"`)
	}
	if _, ok := uruo.mutation.RoleID(); uruo.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UserRole.role"`)
	}
	return nil
}

func (uruo *UserRoleUpdateOne) sqlSave(ctx context.Context) (_node *UserRole, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userrole.Table,
			Columns: userrole.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: userrole.FieldID,
			},
		},
	}
	id, ok := uruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userrole.FieldID)
		for _, f := range fields {
			if !userrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uruo.mutation.CreatedBy(); ok {
		_spec.SetField(userrole.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.AddedCreatedBy(); ok {
		_spec.AddField(userrole.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.UpdatedBy(); ok {
		_spec.SetField(userrole.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(userrole.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.UpdatedAt(); ok {
		_spec.SetField(userrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uruo.mutation.DeletedAt(); ok {
		_spec.SetField(userrole.FieldDeletedAt, field.TypeTime, value)
	}
	if uruo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uruo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uruo.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: role.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uruo.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: role.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserRole{config: uruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
